### ISSUE TITLE
Fix issue with script that extract VALIDATOR_ADDRESS

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-bridge#43]
In case when `NODE_ENV` is not set to `test` an error occurs while trying to extract `VALIDATOR_ADDRESS` from `VALIDATOR_ADDRESS_PRIVATE_KEY`:
```
"path.js:28", 
        "    throw new TypeError('Path must be a string. Received ' + inspect(path));", 
        "    ^", 
        "", 
        "TypeError: Path must be a string. Received undefined", 
        "    at assertPath (path.js:28:11)", 
        "    at Object.join (path.js:1236:7)", 
        "    at Object.<anonymous> (/bridge/src/services/logger.js:5:50)", 
        "    at Module._compile (module.js:653:30)", 
        "    at Object.Module._extensions..js (module.js:664:10)", 
        "    at Module.load (module.js:566:32)", 
        "    at tryModuleLoad (module.js:506:12)", 
        "    at Function.Module._load (module.js:498:3)", 
        "    at Module.require (module.js:597:17)", 
        "    at require (internal/module.js:11:18)"
```

**Comment by ArseniiPetrovich** [comment]
Wrong branch were used. Closing as non-relevant.
